-- 002_rls_policies.sql
CREATE OR REPLACE FUNCTION is_admin() RETURNS BOOLEAN AS $$ BEGIN RETURN EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('ADMIN', 'SUPER_ADMIN')); END; $$ LANGUAGE plpgsql SECURITY DEFINER;
CREATE OR REPLACE FUNCTION is_owner(record_user_id UUID) RETURNS BOOLEAN AS $$ BEGIN RETURN auth.uid() = record_user_id; END; $$ LANGUAGE plpgsql SECURITY DEFINER;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles" ON profiles FOR SELECT USING (is_admin());
CREATE POLICY "Admins can update all profiles" ON profiles FOR UPDATE USING (is_admin());
CREATE POLICY "Admins can insert profiles" ON profiles FOR INSERT WITH CHECK (is_admin());
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read settings" ON site_settings FOR SELECT USING (TRUE);
CREATE POLICY "Only admins can modify settings" ON site_settings FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE feature_flags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read feature flags" ON feature_flags FOR SELECT USING (TRUE);
CREATE POLICY "Only admins can modify feature flags" ON feature_flags FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read enabled payment methods" ON payment_methods FOR SELECT USING (enabled = TRUE OR is_admin());
CREATE POLICY "Only admins can modify payment methods" ON payment_methods FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE registration_payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own registration payments" ON registration_payments FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Users can insert own registration payments" ON registration_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Only admins can update registration payments" ON registration_payments FOR UPDATE USING (is_admin());
ALTER TABLE membership_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read active plans" ON membership_plans FOR SELECT USING (active = TRUE OR is_admin());
CREATE POLICY "Only admins can modify plans" ON membership_plans FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE memberships ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own membership" ON memberships FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Only admins can modify memberships" ON memberships FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE membership_payments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own membership payments" ON membership_payments FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Users can insert own membership payments" ON membership_payments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Only admins can update membership payments" ON membership_payments FOR UPDATE USING (is_admin());
ALTER TABLE task_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read active categories" ON task_categories FOR SELECT USING (active = TRUE OR is_admin());
CREATE POLICY "Only admins can modify categories" ON task_categories FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read active tasks" ON tasks FOR SELECT USING (status = 'ACTIVE' OR is_admin());
CREATE POLICY "Only admins can modify tasks" ON tasks FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE task_submissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own submissions" ON task_submissions FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Users can insert own submissions" ON task_submissions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Only admins can update submissions" ON task_submissions FOR UPDATE USING (is_admin());
ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own wallet" ON wallets FOR SELECT USING (auth.uid() = user_id OR is_admin());
ALTER TABLE wallet_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own transactions" ON wallet_transactions FOR SELECT USING (auth.uid() = user_id OR is_admin());
ALTER TABLE withdrawals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own withdrawals" ON withdrawals FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Users can insert own withdrawals" ON withdrawals FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Only admins can update withdrawals" ON withdrawals FOR UPDATE USING (is_admin());
ALTER TABLE payout_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage own payout accounts" ON payout_accounts FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all payout accounts" ON payout_accounts FOR SELECT USING (is_admin());
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own notifications" ON notifications FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Users can update own notifications" ON notifications FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Admins can insert notifications" ON notifications FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "Admins can update all notifications" ON notifications FOR UPDATE USING (is_admin());
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read active announcements" ON announcements FOR SELECT USING (active = TRUE OR is_admin());
CREATE POLICY "Only admins can modify announcements" ON announcements FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own referrals" ON referrals FOR SELECT USING (auth.uid() = referrer_id OR auth.uid() = referred_id OR is_admin());
CREATE POLICY "Only admins can modify referrals" ON referrals FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE referral_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own referral transactions" ON referral_transactions FOR SELECT USING (auth.uid() = referrer_id OR is_admin());
ALTER TABLE bonuses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read active bonuses" ON bonuses FOR SELECT USING (active = TRUE OR is_admin());
CREATE POLICY "Only admins can modify bonuses" ON bonuses FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE user_bonuses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own bonuses" ON user_bonuses FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Only admins can insert user bonuses" ON user_bonuses FOR INSERT WITH CHECK (is_admin());
ALTER TABLE user_limits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own limits" ON user_limits FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Only admins can modify user limits" ON user_limits FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE user_overrides ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own overrides" ON user_overrides FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Only admins can modify overrides" ON user_overrides FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read tags" ON tags FOR SELECT USING (TRUE);
CREATE POLICY "Only admins can modify tags" ON tags FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE user_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own tags" ON user_tags FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Only admins can modify user tags" ON user_tags FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE user_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Only admins can view notes" ON user_notes FOR SELECT USING (is_admin());
CREATE POLICY "Only admins can insert notes" ON user_notes FOR INSERT WITH CHECK (is_admin());
CREATE POLICY "Only admins can delete notes" ON user_notes FOR DELETE USING (is_admin());
ALTER TABLE support_tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own tickets" ON support_tickets FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Users can insert own tickets" ON support_tickets FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Only admins can update tickets" ON support_tickets FOR UPDATE USING (is_admin());
ALTER TABLE support_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view messages in own tickets" ON support_messages FOR SELECT USING (EXISTS (SELECT 1 FROM support_tickets WHERE id = ticket_id AND (user_id = auth.uid() OR is_admin())));
CREATE POLICY "Users can insert messages in own tickets" ON support_messages FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM support_tickets WHERE id = ticket_id AND (user_id = auth.uid() OR is_admin())));
ALTER TABLE user_activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own activity" ON user_activity_logs FOR SELECT USING (auth.uid() = user_id OR is_admin());
CREATE POLICY "Only admins can insert activity logs" ON user_activity_logs FOR INSERT WITH CHECK (is_admin() OR auth.uid() = user_id);
ALTER TABLE admin_audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Only admins can view audit logs" ON admin_audit_logs FOR SELECT USING (is_admin());
CREATE POLICY "Only admins can insert audit logs" ON admin_audit_logs FOR INSERT WITH CHECK (is_admin());
ALTER TABLE error_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can insert error logs" ON error_logs FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Only admins can view error logs" ON error_logs FOR SELECT USING (is_admin());
ALTER TABLE content_pages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read content pages" ON content_pages FOR SELECT USING (TRUE);
CREATE POLICY "Only admins can modify content pages" ON content_pages FOR ALL USING (is_admin()) WITH CHECK (is_admin());
ALTER TABLE content_sections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read active content sections" ON content_sections FOR SELECT USING (active = TRUE OR is_admin());
CREATE POLICY "Only admins can modify content sections" ON content_sections FOR ALL USING (is_admin()) WITH CHECK (is_admin());
